% This script contains the code used to generate Fig. 5 in the main text.
% To generate this figure, it loads data (saved as 'Data_s=...') that was
% generated by iterating the theoretical population genetic model described
% in Supp. Info. 4. The theoretical population genetic model was iterated
% using the 'Generate_Data' script.

close all
clearvars
clc

sR = [0.1:0.1:0.5]; % Range of plasmid loss rates plotted.

colours = [0, 0.4470, 0.7410 ; 0.8500, 0.3250, 0.0980 ; 0.9290, 0.6940, 0.1250 ; 0.4940, 0.1840, 0.5560 ; 0.4660, 0.6740, 0.1880];	 % Range of colours to be used in the plot.	
  
figure
hold on

for curs = 1:numel(sR) % Loop over plasmid loss rates, so that plot can be built up bit by bit.
    
    s=sR(curs); % Plasmid loss
   
load("Data_s="+s+".mat") % Load saved data. Each data file contains data for a given plasmid loss rate (s).

% The following 16 lines of code plot, for a given plasmid loss rate (s), 
% lines demarcating when cooperation is below fixation from when 
% cooperation is at fixation.
resline2 = res_coop>0.99999 ; % This matrix shows when cooperation is at fixation
X = nR;
YYY = resline2 - [resline2(2:length(resline2(:,1)),:); zeros(1,length(resline2(1,:)))];
Ymin=zeros(1,length(resline2(1,:)));
Ymax=zeros(1,length(resline2(1,:)));
for ii = 1: length(resline2(1,:))
    if find(YYY(:,ii))>0
Ymin(ii) =  min(betaR(find(YYY(:,ii))));
Ymax(ii) =  max(betaR(find(YYY(:,ii))));
    else
        Ymin(ii) =  0;
        Ymax(ii) =  0;
    end
end
plot(X(1./nR*B-CG >0& Ymin<1),Ymin(1./nR*B-CG >0& Ymin<1),'color','k','Linestyle','-','LineWidth',1,'Color',colours(curs,:))
plot(X(1./nR*B-CG >0& Ymax<1),Ymax(1./nR*B-CG >0& Ymax<1),'color','k','Linestyle','-','LineWidth',1,'Color',colours(curs,:))


% The following 6 lines of code add in horizontal lines to connect up the
% areas encapsulated by the coloured lines. Additional lines need to be
% added in because the areas were not generated under high enough
% resolution for the lines to connect up themselves.
if s<0.4
aaa = Ymin(1./nR*B-CG >0& Ymin<1);
bbb = nR(1./nR*B-CG >0& Ymin<1);
line([bbb(1),bbb(1)],[aaa(1),1] ,'Color',colours(curs,:),'LineWidth',1)
line([bbb(end),B/CG],[aaa(end),aaa(end)] ,'Color',colours(curs,:),'LineWidth',1)
end

% The following 16 lines of code plot, for a given plasmid loss rate (s), 
% lines demarcating when cooperation is above zero (loss) from when 
% cooperation is at zero (loss).
resline3 = res_coop > 0.00001 ;
X = nR;
YYY = abs(resline3 - [resline3(2:length(resline3(:,1)),:); zeros(1,length(resline3(1,:)))]);
Ymin=zeros(1,length(resline3(1,:)));
Ymax=zeros(1,length(resline3(1,:)));
for ii = 1: length(resline3(1,:))
    if find(YYY(:,ii))>0
Ymin(ii) =  min(betaR(find(YYY(:,ii))));
Ymax(ii) =  max(betaR(find(YYY(:,ii))));
    else
        Ymin(ii) =  0;
        Ymax(ii) =  0;
    end
end
plot(X(1./nR*B-CG <0 & Ymin>0),Ymin(1./nR*B-CG <0 & Ymin>0),'color','k','Linestyle','-','LineWidth',1,'Color',colours(curs,:))
plot(X(1./nR*B-CG <0 & Ymax>0),Ymax(1./nR*B-CG <0 & Ymax>0),'color','k','Linestyle','-','LineWidth',1,'Color',colours(curs,:))

% The following 14 lines of code add in vertical lines to connect up the
% areas encapsulated by the coloured lines. Additional lines need to be
% added in because the areas were not generated under high enough
% resolution for the lines to connect up themselves.
line([nR(find(Ymin,1,'last')) , nR(find(Ymin,1,'last'))],[Ymin(find(Ymin,1,'last')) , Ymax(find(Ymin,1,'last'))],'Color',colours(curs,:),'LineWidth',1)
aaa2 = Ymin(1./nR*B-CG <0 );
bbb2 = nR(1./nR*B-CG <0 );
line([B/CG,bbb2(1)],[aaa2(1),aaa2(1)],'Color',colours(curs,:),'LineWidth',1)
if s<0.4
line([B/CG,B/CG],[aaa(end),aaa2(1)],'Color',colours(curs,:),'LineWidth',1)
end
if s==0.4
line([B/CG,B/CG],[aaa2(1),1],'Color',colours(curs,:),'LineWidth',1)
end
line([min(nR),max(nR)],[1,1],'Color',[0.15 0.15 0.15],'LineWidth',1)
line([min(nR),max(nR)],[0,0],'Color',[0.15 0.15 0.15],'LineWidth',1)
line([min(nR),min(nR)],[0,1],'Color',[0.15 0.15 0.15],'LineWidth',1)
line([max(nR),max(nR)],[0,1],'Color',[0.15 0.15 0.15],'LineWidth',1)
end

% The following 10 lines of code are for formatting the figure.
set(gcf,'color','white')
xlim([1 28])
box on
axis([min(nR) max(nR) min(betaR) max(betaR)])
yspace=min(betaR):max(betaR)/10:max(betaR);
yticks([yspace]);
yticklabels({yspace});
xspace = min(nR):max(nR)/10:max(nR);
xticks([xspace])
xticklabels({xspace})

% A dotted line is added to show when cooperation is favoured at individual level.
line([B/CG,B/CG],[0,1],'color','k','Linestyle',':','LineWidth',2) 
hold off